use_frameworks!

platform :ios, '10.0'

target 'CustomCoxcombLibrary_Example' do
  pod 'CustomCoxcombLibrary', :path => '../'

  target 'CustomCoxcombLibrary_Tests' do
    inherit! :search_paths

    
  end
end
